'''
Table Fields shouldn't change to often, use config to change once and affect all
'''
CAMPAIGN_ID = 'campaingid'
USERNAME = 'username'
ACTIVE = 'active'
PAYMENT_STATUS = 'payment_status'
CREATED_TIMESTAMP = 'created_timestamp'
SLOGAN = 'slogan'
BUDGE_AMOUNT = 'budge_amount'
BUDGET_CURRENCY = 'budge_currency'
SEARCH_TERMS = 'search_terms'
PHONE_NUMBER = 'phone_number'
WEBSITE = 'website'
DESCRIPTION = 'description'
BUSINESS_NAME = 'business_name'
HISTORY = 'history'
LOCATION = 'location'

'''
Fields to extract from chatbot Request
'''
QUERY_REQUEST = 'queryResult'
PARAMETERS = 'parameters'
BUDGET = 'budget'
AMOUNT = 'amount'
CURRENCY = 'currency'
COUNTRY = 'country'
